### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by CZModding** [LakeYS/Discord-Trivia-Bot#187]
![image](https://user-images.githubusercontent.com/28998760/81156200-c1f2c280-8f96-11ea-9665-15bfbe1cb3b3.png)

Please fix this issue. It is not allowing us to do anything except trivia help

**Comment by LakeYS** [comment]
Hello. This is a result of the database being offline. See the notice on https://opentdb.com/ for more info. 

As it stands, the only thing that can be done about this is to wait for the database to return to full function, or look at self-hosting (https://lakeys.net/triviabot/install.html) and using custom questions. Sorry for the inconvenience.
