### ISSUE TITLE
Change run.sh to work when called from any folder

### ISSUE THREAD

**Issue by Peterr-K** [LakeYS/Discord-Trivia-Bot#206]
Hi

please change run.sh so it can be called from any folder. Now it only works when called from the folder, where bot is installed.

thanks!

**Comment by LakeYS** [comment]
The run.sh file is intended as a quick launch from the respective folder. I would advise creating a specialized run script if there is need to start the bot from outside this folder. (i.e. you can create a script that contains the following line: `/path/to/TriviaBot/run.sh` or `cd /path/to/TriviaBot && node index.js` to accomplish this)
