### ISSUE TITLE
DiscordAPIError: Cannot send messages to this user

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#21]
This occurs when a user has turned off DMs from servers. Can be handled with a warning message to the user.

**Comment by LakeYS** [comment]
Fixed in https://github.com/LakeYS/Discord-Trivia-Bot/commit/199870ca5c53f5c3605ad8b94df07da54d5c90da

**Comment by xXSupernaturalBuilderXx** [comment]
not fixed
