### ISSUE TITLE
Idea: Send categories list in main channel

### ISSUE THREAD

**Issue by Peterr-K** [LakeYS/Discord-Trivia-Bot#211]
Hi

can bot send categories list in the channel where "!categories" was written? it can be an option in config but maybe let it be automatic, when there is less than 15 categories, write it in the main channel. Yes, this is usefull for self hosted situations.

thanks!

**Comment by LakeYS** [comment]
This does make sense for self-hosted bots with smaller category lists. Can look at this soon

**Comment by LakeYS** [comment]
This is now a confirmed plan for the slash command update. Further info will be posted on the [Trello](https://trello.com/c/bsNIgDhZ/71-triviabot-v20-slash-commands-and-code-rework) rather than here.
