### ISSUE TITLE
DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#24]
Cause unknown, currently investigating.

Have found no information about error online. Only lead is that it appears to happen when the bot joins certain guilds.

EDIT: This also appears to occur when adding reactions to messages (guild text channels only, DMs work fine).

EDIT 2: This issue will be closed if there is no new information or occurrences by March 1.

**Comment by yangtang17** [comment]
@LakeYS Any update on this issue? I'm getting this bug when adding my bot to another server.

Here is the log
```
(node:89055) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Access
(node:89055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LakeYS** [comment]
@yangtang17 I have not found anything new on this issue yet. In fact, I don't think I have encountered the issue in a while.

If you haven't already, try adding the `--trace-warnings` argument (e.g. `node --trace-warnings index.js`). This should show you where the promise rejection is so you can try to narrow down the cause. 

Please do let me know if you find anything.

**Comment by LakeYS** [comment]
I have not encountered this issue in recent months, however this issue still appears to be gaining a fair amount of views. Unfortunately, I am not sure what the cause is or what fixed it, nor was I ever able to replicate it. It simply went away like it never happened.

For those reading, if you find a fix or any helpful information, please post it here for other developers that find their way here. Thanks.

See also: [Opcodes and Status Codes](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes) ("Missing Access" is code 50001)

**Comment by LakeYS** [comment]
I have made adjustments regarding this error. Refer to commit 320219a and "EDIT 3" in the description of this issue.
