### ISSUE TITLE
Case insensivity

### ISSUE THREAD

**Issue by Mte90** [LakeYS/Discord-Trivia-Bot#246]
As now detect as different if a letter is uppercase or not as example. It should confirm that is right anyway.

**Comment by LakeYS** [comment]
Sorry, I'm not sure I understand what this is in reference to. Is this regarding typed letter answers or hangman?

**Comment by Mte90** [comment]
In my tests in hangman mode if the answer is uppercase and someone write fully in lowercase is not detected as right.

**Comment by LakeYS** [comment]
Can you provide more details on your configuration? I am not able to replicate this on 1.x or 2.0

![image](https://user-images.githubusercontent.com/13769484/145724496-2920235c-b70f-4e87-98c5-380a1231f3a8.png)

**Comment by Mte90** [comment]
We can close there was only a case on my tests but I am not able to replicate.
