### ISSUE TITLE
Facing error

### ISSUE THREAD

**Issue by Bhavy11111** [LakeYS/Discord-Trivia-Bot#253]
![Screenshot_2022_0224_135909](https://user-images.githubusercontent.com/100022376/155487264-e281d7a3-159e-446d-baa1-cd4866546344.jpg)
 
I am facing this error when I am trying to make my bot using this source on replit 
Can you pls help ..

**Comment by LakeYS** [comment]
It looks like the system you are running TriviaBot on is using an unsupported version of Node.js. One of our core dependencies, discord.js, requires Node.js version 16.6.0 or higher.
